name: build

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      test:
        required: false
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Version
        id: version_step
        run: |
          # get commit hash
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 'build package' 
        uses: DuckSoft/build-aur-action@master
        with:
          repo-name: linuxqq



      # - name: Release and upload assets
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}   

      - name: GitHub Push        
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: false
          artifacts: "./*/*.zst"
          tag: ${{ env.COMMIT_HASH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          skipIfReleaseExists: true
          replacesArtifacts: true
    
